# Generated by Django 3.0.3 on 2020-07-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0003_auto_20200730_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
    ]
