# Generated by Django 3.0.3 on 2020-08-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0005_auto_20200731_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='contact_pic'),
        ),
    ]
